defaults:
  - _self_
  - env: hopper

#These params are turned already
seeds: 
- 0
- 1
#- 2: Not enough resources to run 3 seeds

tag: null
vec_envs: 1

train:
  lr: 5e-5
  weight_decay: 2e-3
  vec_envs: ${vec_envs}
  env_name: ${env.env_name}
  train_steps: 50_000
  finetune_steps: 10_000
  batch_size: 512
  plot_interval: 500
  eval_interval: 500
  eval_episodes: 10
  warmup_steps: 20_000
  gradient_clip_value: 1.0
  finetune_weight_decay: 5e-4
  rtg_target: ${env.rtg_target}
  eval_drop_ps: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

buffer:
  _target_: buffer.SequenceBuffer
  env_name: ${env.env_name}
  dataset: medium
  sample_type: traj_length
  context_len: ${model.context_len}
  gamma: 1.0
  drop_cfg:
    drop_fn: const
    drop_p: 0.6
    finetune_drop_p: 0.5
    update_interval: 500
    drop_aware: ${model.drop_aware}
  
model:
  _target_: model.DecisionTransformer
  n_heads: 4
  n_blocks: 4
  drop_p: 0.2
  hidden_dim: 512
  context_len: 20
  reward_scale: 1000
  max_timestep: ${env.max_timestep}
  drop_aware: true

hydra:
  job:
    chdir: true
  run:
    dir: ./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}
